FROM centos:7
MAINTAINER sergey.kn92@gmail.com

RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
    && yum -y install yum-utils

RUN yum -y install http://rpms.remirepo.net/enterprise/remi-release-7.rpm \
    && yum-config-manager --enable remi-php72 \
    && yum -y update

RUN yum -y install php-fpm \
                php-cli \
                php-common \
                php-xml \
                php-gd \
                php-intl \
                php-json \
                php-mbstring \
                php-mysqlnd \
                php-pdo \
                php-opcache \
                php-maxminddb

RUN yum -y install pecl \
                php-pecl-amqp \
                php-pecl-imagick \
                php-pecl-zip \
                php-pecl-rdkafka \
                php-pecl-redis \
                php-pecl-xdebug

RUN mkdir /run/php-fpm \
    && mkdir -p /var/www/pp
RUN chmod -R 0777 /run/php-fpm
RUN groupadd www-data
RUN useradd -d /var/www/pp -g www-data www-data

EXPOSE 9000
WORKDIR /var/www/pp
VOLUME ["/var/log/php"]
CMD ["php-fpm", "-F"]