FROM php:7.2.11-fpm-alpine
MAINTAINER sergey.kn92@gmail.com

RUN apk add \
        autoconf \
        make \
        gcc \
        g++ \
        bash \
        bash-completion \
        curl-dev \
        libtool

RUN apk add \
        icu-dev \
        imagemagick-dev \
        pcre-dev \
        freetype-dev \
        libintl \
        libjpeg-turbo-dev \
        libpng-dev \
        libltdl \
        libxml2-dev \
        libzip-dev \
        rabbitmq-c-dev \
        librdkafka-dev

# Устанавливаем расширения для PHP
RUN docker-php-ext-configure gd \
        --with-gd \
        --with-freetype-dir=/usr/include/ \
        --with-png-dir=/usr/include/ \
        --with-jpeg-dir=/usr/include/

RUN docker-php-ext-configure zip --with-libzip

RUN docker-php-ext-install \
        gd \
        intl \
        opcache \
        pdo_mysql \
        zip

RUN pecl install imagick && docker-php-ext-enable imagick
RUN pecl install amqp && docker-php-ext-enable amqp
RUN pecl install rdkafka && docker-php-ext-enable rdkafka

WORKDIR /var/www/pp
VOLUME ["/var/log/php"]
CMD php-fpm