version: '3.4'

networks:
  default:
    ipam:
      config:
        - subnet: 172.37.37.0/24

services:

  # Nginx
  nginx:
    image: nginx:1.17.9-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      default:
        ipv4_address: 172.37.37.10
    volumes:
      - ./:/var/www/test
      - ./docker/logs/nginx:/var/log/nginx
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/config.template:ro
    depends_on:
      - php
    environment:
      NGINX_HOST: ${BASE_DOMAIN}
    cap_add:
      - SYS_TIME
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/config.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  # PHP-FPM
  php:
    build: ./images/php
    container_name: php
    expose:
      - 9000
    networks:
      default:
        ipv4_address: 172.37.37.11
    volumes:
      - ./:/var/www/test
      - ./docker/logs/php:/var/log/php
      - ./docker/php/php.ini:/etc/php/php.ini:ro
      - ./docker/php/www.conf:/etc/php-fpm.d/www.conf:ro
    depends_on:
      - mysql
    cap_add:
      - SYS_TIME

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    expose:
      - 3306
    ports:
      - 127.0.0.1:3306:3306
    networks:
      default:
        ipv4_address: 172.37.37.12
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
      - ./docker/logs/mysql:/var/log/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    cap_add:
      - SYS_TIME
